development:
  adapter: postgresql
  encoding: unicode
  database: ssrk # name your development app something
  host: localhost
  pool: 5
  username: postgres
  password: password 


  production:
  adapter: postgresql
  encoding: unicode
  database: ssrk
  pool: 5
  username: postgres
  password: password